---
name: collectd

instance_groups:
- name: collectd
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: collectd
    release: collectd
    properties:
      collectd:
        config: |
          LoadPlugin "df"
          LoadPlugin "disk"
          LoadPlugin "cpu"
          LoadPlugin "load"
          LoadPlugin "write_graphite"
          <Plugin "write_graphite">
            <Node "">
              EscapeCharacter "."
              Host "localhost"
              Port "2003"
            </Node>
          </Plugin>

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: collectd
  sha1: 58970c443385380951306a755b4ee2bb405cdd80
  stemcell:
    os: ubuntu-xenial
    version: "97.28"
  url: https://s3.amazonaws.com/collectd-boshrelease/compiled-releases/collectd/collectd-2.2.3-ubuntu-xenial-97.28-20181028-012725-46629094-20181028012725.tgz
  version: 2.2.3
