---
name: collectd

instance_groups:
- name: collectd
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: collectd
    release: collectd
    properties:
      collectd:
        config: |
          LoadPlugin "df"
          LoadPlugin "disk"
          LoadPlugin "cpu"
          LoadPlugin "load"
          LoadPlugin "write_graphite"
          <Plugin "write_graphite">
            <Node "">
              EscapeCharacter "."
              Host "localhost"
              Port "2003"
            </Node>
          </Plugin>

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: collectd
  sha1: eda558d2fb37e5087b8ab69cf238a13c023afba4
  stemcell:
    os: ubuntu-xenial
    version: "456.3"
  url: https://github.com/cloudfoundry-community/collectd-boshrelease/releases/download/v2.2.4/collectd-2.2.4.tgz
  version: 2.2.4
